// jobs.js

const jobs = [
    {
      id: 1,
      jobTitle: 'Software Engineer',
      location: 'San Francisco, CA',
      jobSummary: 'Develop and maintain software applications...',
      payPackage: '$40 -$50 Hr',
      sector: 'Engineering',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are looking for a skilled software engineer...',
      offeringCompany: 'TechCo Solutions',
      offeringCompanyWebsite: 'https://techco.com',
      socialMedia: {
        twitter: 'https://twitter.com/techco',
        linkedIn: 'https://linkedin.com/company/techco',
      },
      companyLogo: 'path/to/techco-logo.png',
    },
  
    {
      id: 2,
      jobTitle: 'Marketing Specialist',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 3,
      jobTitle: 'Data Analyst',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: false,
      remote_work: true,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 4,
      jobTitle: 'Marketing Manager',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: false,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 5,
      jobTitle: 'Security Analyst',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 6,
      jobTitle: 'CEO',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 7,
      jobTitle: 'CFO Marketing',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 8,
      jobTitle: 'Technical Writer',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 9,
      jobTitle: 'Marketing Specialist',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 10,
      jobTitle: 'Marketing Specialist',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 11,
      jobTitle: 'Marketing Specialist',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 12,
      jobTitle: 'Marketing Specialist',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 13,
      jobTitle: 'Marketing Specialist',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
    {
      id: 14,
      jobTitle: 'Marketing Specialist',
      location: 'New York, NY',
      jobSummary: 'Create and execute marketing campaigns...',
      payPackage: '$60,000 - $80,000',
      sector: 'Marketing',
      fullTime: true,
      remote_work: false,
      detailedInfo: 'We are seeking a talented marketing specialist...',
      offeringCompany: 'MarketingPro Inc.',
      offeringCompanyWebsite: 'https://marketingpro.com',
      socialMedia: {
        twitter: 'https://twitter.com/marketingpro',
        linkedIn: 'https://linkedin.com/company/marketingpro',
      },
      companyLogo: 'path/to/marketingpro-logo.png',
    },
  
  ];
  
  export default jobs;
  